### ISSUE TITLE
Host via Vercel

### ISSUE THREAD

**Issue by KendallDoesCoding** [Kira272921/solidity-quickstart#7]
Host website on [Vercel](https://vercel.com/)

**Comment by Kira272921** [comment]
Hey 👋, I haven't made any website for this repository yet. Would make one later on :D

**Comment by KendallDoesCoding** [comment]
> Hey 👋, I haven't made any website for this repository yet. Would make one later on :D

Oh, I thought this was a website xD. If you host a website, I suggest Netlify for HTML, CSS, JS
